config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, except: [:index]
  resources :dishes, except: [:index]
  root 'home#index'
  post 'events/:id/join', to: 'events#join', as: 'join_event'
  post 'events/:id/leave', to: 'events#leave', as: 'leave_event'
  get 'events/:id/draw', to: 'events#draw', as: 'draw_ingredient_style'
  get 'events/:id/reset', to: 'events#reset', as: 'reset_ingredient_style'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# #TODO: Documentation
class HomeController < ApplicationController
  # #TODO: Documentation
  def index
    @dishes = Dish.all
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_login_form.html.erb
<%= form_for(:user, :url => session_path(:user)) do |f| %>
  <div class="field form-group py-1">
    <%= f.text_field :email, placeholder: t('login_form.account_placeholder'), required: true, autocomplete: true, class: "form-control" %>
  </div>

  <div class="field form-group py-1">
    <%= f.password_field :password, placeholder: t('login_form.password_placeholder'), required: true, autocomplete: true, class: "form-control"  %>
  </div>

  <div class="row py-1 ">
    <div class="col">
      <div class="field form-group text-end">
        <%= f.check_box :remember_me %>
        <%= f.label t('login_form.remember_me') %>
      </div>
    </div>
  </div>

  <%= f.submit t('login_form.sign_in_btn'), class: "btn btn-primary form-control py-1" %>

  <div class="row justify-content-end py-1 ">
    <div class="col">
      <%= link_to t('login_form.sign_up_btn'), new_user_registration_path, class: "btn btn-secondary btn-sm w-100" %>
    </div>
  </div>
  <div class="row justify-content-end py-1 ">
    <div class="col">
      <%= link_to t('login_form.forgot_password_btn'), new_password_path(:user), class: "btn btn-secondary btn-sm w-100" %>
    </div>
  </div>

<% end %>

app/views/home/_user_menu.html.erb
<div class="d-grid gap-2">
  <%= link_to t('index.my_account'), edit_user_registration_path, class: "btn btn-secondary" %>
  <%= link_to t('index.create_room'), new_event_path, class: "btn btn-primary" %>
</div>

app/views/home/index.html.erb
<div class="container-fluid mt-4">
  <div class="container-fluid  p-0 position-relative">
    <%= image_tag 'favicon.svg'%>
    <% if user_signed_in? %>
      <%= button_to t('index.logout'), destroy_user_session_path, method: :delete, class: "btn-sm position-absolute top-0 end-0" %>
      <h2><%= t('index.greeting_signed_in', user_name: current_user.name) %></h2>
    <% else %>
      <h2><%= t('index.greeting_anonymous') %></h2>
    <% end %>


    <div class="row">
      <div class="col-md-4 py-2">
        <% if user_signed_in? %>
          <%= render 'user_menu' %>
        <% else %>
          <%= render 'login_form', locals: { resource: current_user, resource_name: :user }%>
        <% end %>
      </div>
      <div class="col-md-8 py-2">
        <%= render "dishes/dish_carousel", dishes: @dishes.where.not(img_url: [nil, ""]).order(Arel.sql('RANDOM()')).first(3) %>
      </div>
    </div>

    <div class="row text-left mt-4">
      <h3><%= t('event.list.upcoming_events') %></h3>
    </div>
    <div class="row d-none d-md-block">
      <div class="col">
        <%= render 'events/event_list', events: Event.all %>
      </div>
    </div>
    <div class="row d-block d-md-none">
      <div class="col">
        <%= render 'events/event_list_sm', events: Event.all %>
      </div>
    </div>
  </div>

</div>