config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, except: [:index]
  resources :dishes, except: [:index]
  root 'home#index'
  post 'events/:id/join', to: 'events#join', as: 'join_event'
  post 'events/:id/leave', to: 'events#leave', as: 'leave_event'
  get 'events/:id/draw', to: 'events#draw', as: 'draw_ingredient_style'
  get 'events/:id/reset', to: 'events#reset', as: 'reset_ingredient_style'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :dishes, dependent: :destroy
  belongs_to :owner, class_name: :User, foreign_key: :owner_id
  has_many :participations, dependent: :destroy
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# #TODO: Documentation
class EventsController < ApplicationController
  before_action :set_event, only: %i[draw reset show edit update destroy join leave]
  before_action :create_room_id, only: %i[new]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show; end

  # POST /events/1/join
  def join
    respond_to do |format|
      if add_participant(current_user.id)
        format.html { redirect_to(event_url(@event)) }
        format.json { render(:show, status: :ok, location: @event) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # POST /events/1/leave
  def leave
    remove_participant(current_user.id)
  end

  # GET /events/1/draw
  def draw
    ::Participation.find_by(user_id: params[:user_id], event_id: @event.id)
                   .update(
                     main_ingredient_id: Ingredient.order(Arel.sql('RANDOM()')).first.id,
                     cuisine_style_id: CuisineStyle.order(Arel.sql('RANDOM()')).first.id
                   )
    respond_to do |format|
      format.html { redirect_to(event_url(@event)) }
    end
  end

  # GET /events/1/reset?user_id=1&event_id=1
  def reset
    Participation.find_by(user_id: params[:user_id], event_id: @event.id)
                   .update(main_ingredient_id: nil, cuisine_style_id: nil)
    respond_to do |format|
      format.html { redirect_to(event_url(@event)) }
    end
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if (@event.save)
        add_participant(current_user.id)
        format.html { redirect_to(event_url(@event)) }
        format.json { render(:show, status: :created, location: @event) }
      else
        format.html { render(:new, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        flash[:success] = t('event.flash.update_succesful')
        format.html { redirect_to(event_url(@event)) }
        format.json { render(:show, status: :ok, location: @event) }
      else
        format.html { render(:edit, status: :unprocessable_entity) }
        format.json { render(json: @event.errors, status: :unprocessable_entity) }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    remove_dishes_upon_cancel_event
    @event.destroy
    respond_to do |format|
      flash[:warning] = t.('event.flash.cancel_successful')
      format.html { redirect_to(root_path) }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:event_date, :title, :max_players, :owner_id, :room_id, :public)
  end

  # Only allow a list of trusted parameters through.
  def participation_params
    params.require(:event).permit(:owner_id)
  end

  def create_room_id
    loop do
      @new_room_id = SecureRandom.urlsafe_base64(4).upcase
      break unless Event.exists?(room_id: @new_room_id)
    end
  end

  def add_participant(user_id)
    if (Participation.where(event_id: @event.id).count < @event.max_players)
      Participation.new(user_id:, event_id: @event.id).save
      return flash['success'] = t('event.flash.join_successful')  if user_id != @event.owner_id
    else
      return flash['danger'] = t('event.flash.join_failed_max')
    end
    return flash['success'] = t('event.flash.create_successful')
  end

  def remove_participant(user_id)
    # TODO: confirmation before leaving/cancelling an event.

    Participation.find_by(user_id:, event_id: @event.id).destroy
    remove_dishes_upon_cancel_event(user_id)

    if user_id == @event.owner_id
      @event.destroy
      flash[:warning] = t('event.flash.cancel_successful', title: @event.title)
    else
      flash[:warning] = t('event.flash.leave_successful', title: @event.title, host: User.find(@event.owner_id).name)
    end

    respond_to do |format|
      format.html { redirect_to(root_path) }
    end
  end

  def remove_dishes_upon_cancel_event(user_id)
    s3 = Aws::S3::Client.new
    if user_id == @event.owner_id
      Dish.where(event_id: @event.id).each do |dish|

        folder_name = "#{@event.event_date.strftime('%y%m%d%H%M%s')}-#{@event.id}"
        filename = dish.img_url.split("/#{folder_name}/").last(1)[0]
        file_key = "#{folder_name}/#{filename}"
        Aws::S3::Resource.new.bucket(folder_name).object(filename).delete

        dish.destroy
      end
    else
      Dish.where(event_id: @event.id, user_id:).each do |dish|

        folder_name = "#{@event.event_date.strftime('%y%m%d%H%M%s')}-#{@event.id}"
        filename = dish.img_url.split("/#{folder_name}/").last(1)[0]
        file_key = "#{folder_name}/#{filename}"
        Aws::S3::Resource.new.bucket(folder_name).object(filename).delete

        dish.destroy
      end
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <div class="row text-center">
    <h2><%= event.title %></h2>
    <p>
      <strong><%= t('event.show.date') %></strong>
      <%= event.event_date %>
    </p>
  </div>

</div>

app/views/events/_event_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= t('event.list.event_name_header') %></th>
      <th scope="col"><%= t('event.list.room_id_header') %></th>
      <th scope="col"><%= t('event.list.max_players_header') %></th>
      <th scope="col"><%= t('event.list.event_date_header') %></th>
      <th scope="col"><%= t('event.list.event_host_header') %></th>
    </tr>
  </thead>
  <tbody>
    <% events.where('event_date >= ?', Date.today).order(:event_date).each do |event| %>
      <tr>
        <td>
          <%= event.title %>
        </td>

        <td>
          <% if user_signed_in? %>
          <%= link_to event.room_id, event, style: "font-family: Monospace;"  %>
          <% else %>
          <span style="font-family: Monospace;"><%= event.room_id %></span>
          <% end %>
        </td>

        <% current_player_count = Participation.where(event_id: event.id).count %>
        <% if current_player_count < event.max_players %>
          <% room_availability = "color: green" %>
        <% else %>
          <% room_availability = "color: grey; font-style: italic" %>
        <% end %>
        <td>
          <span style="<%= room_availability %>"><%= current_player_count %>/<%= event.max_players %></span>
        </td>

        <td>
          <i><%= event.event_date %></i>
        </td>

        <td>
          <strong><i><%= User.find_by(id: event.owner).name %></i></strong>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_event_list_sm.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= t('event.list.room_id_header') %></th>
      <th scope="col"><%= t('event.list.event_date_header') %></th>
      <th scope="col"><%= t('event.list.event_host_header') %></th>
    </tr>
  </thead>
  <tbody>
  <% events.where('event_date >= ?', Date.today).order(:event_date).each do |event| %>
    <tr>
      <td>
        <% if user_signed_in? %>
        <%= link_to event.room_id, event, style: "font-family: Monospace;" %>
        <% else %>
        <span style="font-family: Monospace;"><%= event.room_id %></span>
        <% end %>
      </td>

      <td>
        <i><%= event.event_date %></i>
      </td>

      <td>
        <strong><i><%= User.find_by(id: event.owner).name %></i></strong>
      </td>
    </tr>
  <% end %>

  </tbody>
</table>

app/views/events/_event_participant_list.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th></th>
      <th scope="col" colspan="1"><%= t('event.participation.participant_header') %></th>
      <th scope="col" colspan="5"><%= t('event.participation.cuisine_style_header') %></th>
      <th scope="col" colspan="5"><%= t('event.participation.main_ingredient_header') %></th>
      <th scope="col" colspan="5"><%= t('event.participation.dish_header') %></th>
    </tr>
  </thead>
  <tbody>
    <% Participation.where(event_id: @event.id).order(:created_at).each do |participation| %>
      <% user = User.find_by(id: participation.user_id) %>
      <tr>

        <td class="text-end">
          <% if user.id == @event.owner_id %>
            <i><strong><%= t('event.participation.host') %></strong></i>
          <% end %>
        </td>

        <td scope="col" colspan="1">
          <% if user.id == @event.owner.id %>
            <i><strong><%= user.name %></strong></i>
          <% else %>
            <%= user.name %>
          <% end %>
          <% if (current_user == user || current_user.id == @event.owner.id) && (participation.main_ingredient_id && participation.cuisine_style_id) %>
            <%= button_to t('event.participation.reset_challenge_btn'), reset_ingredient_style_path, params: {event_id: @event.id, user_id: user.id}, method: :get, class: "btn-sm btn-secondary w-100" %>
          <% end %>
        </td>

        <% if participation.main_ingredient_id && participation.cuisine_style_id %>
          <td scope="col" colspan="5">
              <%= CuisineStyle.find(participation.cuisine_style_id).name %>
          </td>
          <td scope="col" colspan="5">
              <%= Ingredient.find(participation.main_ingredient_id).name %>
          </td>

        <% else %>
          <td scope="col" colspan="10">
            <% if current_user == user %>
              <%= button_to t('event.participation.draw_challenge_btn'), draw_ingredient_style_path, params: {event_id: @event.id, user_id: user.id}, method: :get, class: "btn-sm btn-primary w-100" %>
            <% elsif current_user.id == @event.owner_id%>
              <%= button_to t('event.participation.draw_challenge_guest_btn'), draw_ingredient_style_path, params: {event_id: @event.id, user_id: user.id}, method: :get, class: "btn-sm btn-secondary w-100" %>
            <% end %>
          </td>
        <% end %>


        <td scope="col" colspan="5">
          <% btn_txt = t('event.participation.upload_dish_btn') %>
          <% Dish.where(event_id: @event.id, user_id: user.id).each do |dish| %>
            <p><%= link_to dish.name, dish_path(dish) %></p>
            <% btn_txt = t('event.participation.upload_more_btn') %>
          <% end %>
          <% if current_user.id == user.id %>
            <%= button_to btn_txt, new_dish_path, params: {event_id: @event.id}, method: :get, class: "btn-sm btn-primary w-100" %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_event_participant_list_sm.html.erb
<table class="table table-hover table-condensed table-striped">
  <thead>
    <tr>
      <th scope="col"><%= t('event.participation.participant_header') %></th>
      <th scope="col"><%= t('event.participation.dish_header') %></th>
    </tr>
  </thead>
  <tbody>
    <% Participation.where(event_id: @event.id).order(:created_at).each do |participation| %>
      <% user = User.find_by(id: participation.user_id) %>
      <tr>
        <td>
          <div class="row">
            <div class="col-6">
              <% if user.id == @event.owner.id %>
                <i><strong><%= user.name %></strong></i>
              <% else %>
                <%= user.name %>
              <% end %>
            </div>
          <% if participation.main_ingredient_id && participation.cuisine_style_id %>
            <div class="col-6">
              <%= CuisineStyle.find(participation.cuisine_style_id).name %>
              <%= Ingredient.find(participation.main_ingredient_id).name %>
            </div>
            <% if (current_user == user || current_user.id == @event.owner.id) && (participation.main_ingredient_id && participation.cuisine_style_id) %>
              <%= button_to t('event.participation.reset_challenge_btn'), reset_ingredient_style_path, params: {event_id: @event.id, user_id: user.id}, method: :get, class: "btn-sm btn-secondary w-100" %>
            <% end %>
          <% else %>
            <% if current_user == user %>
              <%= button_to t('event.participation.draw_challenge_btn'), draw_ingredient_style_path, params: {event_id: @event.id, user_id: user.id}, method: :get, class: "btn-sm btn-primary w-100" %>
            <% elsif current_user.id == @event.owner_id%>
              <%= button_to t('event.participation.draw_challenge_guest_btn'), draw_ingredient_style_path, params: {event_id: @event.id, user_id: user.id}, method: :get, class: "btn-sm btn-secondary w-100" %>
            <% end %>
          </td>
          <% end %>

        </td>

        <td>
          <% btn_txt = t('event.participation.upload_dish_btn') %>
          <% Dish.where(event_id: @event.id, user_id: user.id).each do |dish| %>
            <p><%= link_to dish.name, dish_path(dish) %></p>
            <% btn_txt = t('event.participation.upload_more_btn') %>
          <% end %>
          <% if current_user.id == user.id %>
            <%= button_to btn_txt, new_dish_path, params: {event_id: @event.id}, method: :get, class: "btn-sm btn-primary w-100" %>
          <% end %>
        </td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
<% if event.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

  <ul>
    <% event.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row my-2">
  <div class="col offset-md-3 col-md-6">
    <%= form.label t('event.form.title') %>
    <%= form.text_field :title, required: true, class: "w-100 d-block p-0" %>
  </div>
</div>

<div class="row my-2">
  <div class="col offset-md-3 col-md-6">
    <%= form.label t('event.form.date') %>
    <%= form.date_field :event_date, required: true, class: "w-100 d-block p-0" %>
  </div>
</div>

<div class="row mt-2">
  <div class="col offset-md-3 col-md-6">
    <%= form.label t('event.form.max_players'), class: "w-100 d-inline" %><span> </span><span id="rangeval" %>2</span>
  </div>
</div>
<div class="row mb-2">
  <div class="col offset-md-3 col-md-6">
    <%= form.range_field :max_players, id: "max_player", in: 1..8, step: 1, value: 2, class: "w-100 d-block", oninput: 'document.getElementById("rangeval").innerText = document.getElementById("max_player").value' %>
  </div>
</div>

<div class="row my-2">
  <div class="col offset-md-3 col-md-6">
    <%= form.hidden_field :owner_id, value: current_user.id, style: "display: block" %>
    <% if @new_room_id %>
    <%= form.hidden_field :room_id, value: @new_room_id, style: "display: block" %>
    <% end %>
  </div>
</div>

<div class="row my-2">
  <div class="col offset-md-3 col-md-6">
    <%= form.submit t('event.form.create_btn'), class: "btn btn-primary w-100 p-0" %>
  </div>
</div>
<% end %>

app/views/events/_history.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= t('event.list.event_name_header') %></th>
      <th scope="col"><%= t('event.list.room_id_header') %></th>
      <th scope="col"><%= t('event.list.max_players_header') %></th>
      <th scope="col"><%= t('event.list.event_date_header') %></th>
      <th scope="col"><%= t('event.list.event_host_header') %></th>
    </tr>
  </thead>
  <tbody>
  <% Event.joins(:participations).where("user_id = ?", current_user.id).order(event_date: :desc).each do |event| %>
      <tr>
        <td>
          <%= event.title %>
        </td>
        <td>
          <% if user_signed_in? %>
          <%= link_to event.room_id, event, style: "font-family: Monospace;"  %>
          <% else %>
          <span style="font-family: Monospace;"><%= event.room_id %></span>
          <% end %>
        </td>
        <td>
          <% current_player_count = Participation.where(event_id: event.id).count %>
          <% if current_player_count < event.max_players && Date.today < event.event_date %>
            <% room_availability = "color: green" %>
          <% else %>
            <% room_availability = "color: grey; font-style: italic" %>
          <% end %>
          <span style="<%= room_availability %>"><%= current_player_count %>/<%= event.max_players %></span>
        <td>
          <i><%= event.event_date %></i>
        </td>
        <td>
          <strong><i><%= User.find_by(id: event.owner).name %></i></strong>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/events/_history_sm.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col"><%= t('event.list.room_id_header') %></th>
      <th scope="col"><%= t('event.list.event_date_header') %></th>
      <th scope="col"><%= t('event.list.event_host_header') %></th>
    </tr>
  </thead>
  <tbody>
  <% Event.joins(:participations).where("user_id = ?", current_user.id).each do |event| %>
      <tr>
        <td>
          <% if user_signed_in? %>
          <%= link_to event.room_id, event, style: "font-family: Monospace;"  %>
          <% else %>
          <span style="font-family: Monospace;"><%= event.room_id %></span>
          <% end %>
        </td>
        <td>
          <i><%= event.event_date %></i>
        </td>
        <td>
          <strong><i><%= User.find_by(id: event.owner).name %></i></strong>
        </td>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/events/edit.html.erb
<div class="container mt-4">
  <h1><%= t('event.edit.title') %></h1>

  <%= render "form", event: @event %>

  <div class="row my-2">
    <div class="col offset-md-4 col-md-4">
      <%= button_to t('common.back_btn'), event_url(@event), method: :get, class: "btn-sm w-100" %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container mt-4">

  <div class="row text-center">
    <h1><%= t('event.new.title') %></h1>
  </div>

  <%= render "form", event: @event %>

  <div class="row my-2">
    <div class="col offset-md-4 col-md-4">
      <%= button_to t('common.back_btn'), root_path, method: :get, class: "btn-sm w-100" %>
    </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container mt-4">

  <%= render @event %>
  <%= render "dishes/dish_carousel", dishes: Dish.where.not(img_url: [nil, ""]).where(event_id: @event.id).order(Arel.sql('RANDOM()')) %>
  <div class="row m-2">
    <h5 ><%= t('event.show.players') %> <%= open_seats = @event.max_players - Participation.where(event_id: @event.id).count %></h5>
  </div>

  <div class="row d-none d-md-block">
    <div class="col">
    <%= render "event_participant_list" %>
    </div>
  </div>
  <div class="row d-block d-md-none">
    <div class="col">
    <%= render "event_participant_list_sm" %>
    </div>
  </div>

  <div class="row my-2">
    <div class="col-3 px-1">
      <%= button_to t('common.back_btn'), root_path, method: :get, class: "btn-sm w-100" %>
    </div>

    <% if current_user.id == @event.owner_id %>
      <div class="col-6 px-1">
        <%= button_to t('common.edit_btn'), edit_event_path(@event), method: :get, class: "btn-sm w-100" %>
      </div>
      <div class="col-3 px-1">
        <%=  button_to t('common.delete_btn'), leave_event_path(@event), class: "btn-danger btn-sm w-100", form: {data: { turbo_confirm: t('event.show.delete_warning') }} %>
      </div>
    <% else %>
      <% if !Participation.find_by(event_id: @event.id, user_id: current_user.id) %>
          <div class="col-6 px-1">
          <% if open_seats %>
              <%= button_to t('event.show.join_btn'), join_event_path(@event), class: "btn-sm w-100" %>
          <% else %>
              <button type="button" class="btn-sm w-100" disabled>Event is full</button>
          <% end %>
          </div>
      <% else %>
        <div class="offset-6 col-3 px-1">
          <%= button_to t('event.show.leave_btn'), leave_event_path(@event), class: "btn-warning btn-sm w-100", form: {data: { turbo_confirm: t('event.show.leave_warning') }}%>
        </div>
      <% end %>
    <% end %>
  </div>
</div>