config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events, except: [:index]
  resources :dishes, except: [:index]
  root 'home#index'
  post 'events/:id/join', to: 'events#join', as: 'join_event'
  post 'events/:id/leave', to: 'events#leave', as: 'leave_event'
  get 'events/:id/draw', to: 'events#draw', as: 'draw_ingredient_style'
  get 'events/:id/reset', to: 'events#reset', as: 'reset_ingredient_style'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/controllers/dishes_controller.rb
# frozen_string_literal: true

# #TODO: Documentation
class DishesController < ApplicationController
  prepend_before_action :set_dish, only: %i[show edit update destroy]

  # GET /dishes or /dishes.json
  def index
    @dishes = ::Dish.all
  end

  # GET /dishes/1 or /dishes/1.json
  # TODO: show full image & description (new field)
  def show; end

  # GET /dishes/new
  def new
    @dish = Dish.new
    @event = Event.find(params[:event_id])
  end

  # GET /dishes/1/edit
  def edit; end

  # POST /dishes or /dishes.json
  def create
    @event = Event.find(params[:dish][:event_id])
    @dish = Dish.new(dish_params)
    file = params[:attachment][:file]
    filename_raw = "#{Time.now.strftime('%y%m%d%H%M%s')}-#{@dish.name}-#{params[:attachment][:file].original_filename}"
    filename = ERB::Util.url_encode(filename_raw).tr('\\\{\^\}\%\`\"\'\]\>\[\~\<\#\|','').downcase
    bucket_name = ENV['AWS_S3_DISH_BUCKET']
    if ENV['RAILS_ENV'] == "development"
      folder_name = bucket_name
      file_key = "#{bucket_name}/#{filename}"
    else
      folder_name = "#{@event.event_date.strftime('%y%m%d%H%M%s')}-#{@event.id}".tr('\\\{\^\}\%\`\"\'\]\>\[\~\<\#\|','').downcase
      file_key = "#{bucket_name}/#{folder_name}/#{filename}"
    end

    object_url = "#{folder_name}/#{filename}"

    @dish.img_url = "#{ENV['AWS_S3_ENDPOINT']}#{object_url}"

    obj = Aws::S3::Resource.new.bucket(folder_name).object(filename)
    obj.upload_file(file)
    obj.copy_from({acl: 'public-read', content_type: 'image/jpeg', metadata_directive: 'REPLACE', copy_source: file_key})

    respond_to do |format|
      if @dish.save
        flash[:success] = 'Dish was successfully created.'
      else
        flash[:danger] = 'Dish was not created.'
      end
      format.html { redirect_to(event_url(@event)) }
    end
  end

  # PATCH/PUT /dishes/1 or /dishes/1.json
  def update
    # TODO: Update S3 image file if uploaded new file
    @event = Event.find(params[:dish][:event_id])
    respond_to do |format|
      if @dish.update(dish_params)
        flash[:success] = 'Dish was successfully updated.'
      else
        flash[:danger] = 'Dish was not updated.'
      end
      format.html { redirect_to(event_url(@event)) }
    end
  end

  # DELETE /dishes/1 or /dishes/1.json
  def destroy
    # TODO: confirmation before deleting a dish.
    @event = Event.find(@dish.event_id)

    folder_name = "#{@event.event_date.strftime('%y%m%d%H%M%s')}-#{@event.id}"
    filename = @dish.img_url.split("/#{folder_name}/").last(1)[0]
    file_key = "#{folder_name}/#{filename}"
    Aws::S3::Resource.new.bucket(folder_name).object(filename).delete

    @dish.destroy

    respond_to do |format|
      flash[:warning] = 'Dish was successfully deleted.'
      format.html { redirect_to(event_url(@dish.event_id)) }
      format.json { head(:no_content) }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_dish
    @dish = Dish.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def dish_params
    params.require(:dish).permit(:name, :user_id, :event_id)
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:dish).permit(:event_id)
  end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/_dish.html.erb
<div id="<%= dom_id dish %>">
  <h1 class="text-center"><%= dish.name %></h1>

  <div class="row">
    <img src=<%= dish.img_url %> class="d-block mx-auto img-fluid" alt="...">
  </div>

</div>

app/views/dishes/_dish_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-inner">

    <% i = 0 %>

    <% dishes.each do |dish| %>

      <% user_name = User.find_by(id: dish.user_id).name %>
      <% event = Event.find_by(id: dish.event_id) %>
      <% participation = Participation.find_by(event_id: event.id, user_id: dish.user_id) %>

      <% if i == 0 %>
        <div class="carousel-item active">
      <% else %>
        <div class="carousel-item">
      <% end %>

      <% i += 1 %>
      <div class="container p-0" style="height: 35vh">
        <img src=<%= dish.img_url %> class="d-block mx-auto img-fluid" alt="...">
      </div>
      <div class="carousel-caption" style="background-color: #00000066">
        <h3><%= dish.name %></h3>
        <p>
          <%= user_name %>
          <br />
          <%= t('dish.carousel.cuisine_style') %>
          <%= participation.cuisine_style_id? ? CuisineStyle.find(participation.cuisine_style_id).name : "" %>
          ｜
          <%= t('dish.carousel.main_ingredient') %>
          <%= participation.main_ingredient_id? ? Ingredient.find(participation.main_ingredient_id).name : "" %>
          <% if !@event %>
            <br />
            <%= event.title %>
            <br />
            <%= event.event_date %>
          <% end %>
        </p>
      </div>
        </div>
      <% end %>
    </div>

    <% if dishes.length > 0 %>

      <div class="carousel-indicators">
        <% i = 0 %>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <% while i < dishes.length - 1 do %>
          <% i += 1 %>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to=<%= i %> aria-label="Slide <%= i %>"></button>
        <% end %>
      </div>

      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>

      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>

    <% else %>
      <div class="row text-center">
        <p>Upload photos of your dishes!</p>
      </div>
    <% end %>
  </div>

app/views/dishes/_form.html.erb
<%= form_with(model: dish) do |form| %>
<% if dish.errors.any? %>
<div style="color: red">
  <h2><%= pluralize(dish.errors.count, "error") %> prohibited this dish from being saved:</h2>

  <ul>
    <% dish.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="row my-2">
  <div class="col">
    <%= form.label t('dish.new.name') %>
    <%= form.text_field :name, required: true, class: "w-100 d-block p-0" %>
  </div>
</div>

<div class="row my-2">
  <div class="col">
    <%= form.file_field :image, required: true, name: "attachment[file]" %>
  </div>
</div>

<div class="row my-2">
  <div class="col">
    <%= form.hidden_field :user_id, value: current_user.id %>

    <% if dish.event_id %>
      <%= form.hidden_field :event_id, value: dish.event_id %>
    <% else %>
      <%= form.hidden_field :event_id, value: params[:event_id] %>
    <% end %>
  </div>
</div>

<div class="row my-2">
  <div class="col">
    <%= form.submit t('dish.new.create_btn'), class: "btn btn-primary w-100 p-0" %>
  </div>
</div>
<% end %>

app/views/dishes/edit.html.erb
<div class="container mt-4">
  <div class="container mt-4">

  <h1><%= t('dish.edit.title') %></h1>

  <%= render "form", dish: @dish %>

  <br>

  <div class="row">
    <div class="col-3 p-0">
      <%= button_to t('common.cancel_btn'), dish_path, method: :get, class: "btn-sm w-100" %>
    </div>
  </div>
</div>
</div>

app/views/dishes/new.html.erb
<div class="container mt-4">

  <div class="row text-center">
    <h1><%= t('dish.new.title') %></h1>
  </div>

  <%= render "form", dish: @dish %>

  <div class="row mx-0">
    <div class="col-3 p-0">
      <%= button_to t('common.back_btn'), event_path(@event.id), method: :get, class: "btn-sm w-100" %>
    </div>
  </div>
</div>

app/views/dishes/show.html.erb
<div class="container mt-4">

  <%= render @dish %>


  <div class="row">
    <div class="dropdown-divider"> </div>
      <p>
      <%# TODO: migrate description field %>
      <%# <% if @dish.description %>
      <%#   <%= @dish.description %>
      <%# <% else %>
      <%= t('dish.made_by_user', user: User.find(@dish.user_id).name) %><%= Event.find(@dish.event_id).event_date%>
      <%# <% end %>
      </p>
    <div class="dropdown-divider"> </div>
  </div>

  <div class="m-2">
    <% if current_user.id == @dish.user_id %>

    <div class="row">
      <div class="col-3 p-0 m-1">
        <%= button_to t('common.edit_btn'), edit_dish_path(@dish), method: :get, class: "btn-sm w-100" %>
      </div>
      <div class="col-3 p-0 m-1">
        <%= button_to t('common.delete_btn'), @dish, method: :delete, class: "btn-danger btn-sm w-100" %>
      </div>

      <% end %>
    </div>
    <div class="row">
      <div class="col-3 p-0 m-1">
        <%= button_to t('common.back_btn'), event_path(@dish.event_id), method: :get, class: "btn-sm w-100" %>
      </div>
    </div>
  </div>

</div>